import type { Metadata } from "next";
import { AR_One_Sans } from 'next/font/google'
import "../styles/globals.css";
import Header from '@/components/header'
import Footer from "@/components/footer";

const sans = AR_One_Sans({
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${sans.className}`}
      >
        <Header />
        <main className="p-1 lg:p-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
